name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies and run tests (Backend)
        run: |
          cd backend
          npm ci
          npm test
      - name: Install dependencies and run tests (Frontend)
        run: |
          cd frontend
          npm ci
          npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
      - name: Deploy to DigitalOcean
        env:
          PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          HOST: ${{ secrets.DIGITALOCEAN_HOST }}
          USER: ${{ secrets.DIGITALOCEAN_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no docker-compose.yml docker-compose.prod.yml $USER@$HOST:~/
          ssh -i private_key -o StrictHostKeyChecking=no $USER@$HOST '
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          '
