name: CI/CD Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Debug - Display Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm ci

      - name: Debug - List installed packages
        run: |
          cd backend
          npm list --depth=0

      - name: Generate tsoa routes
        run: |
          cd backend
          npm run build

      - name: Run tests (Backend)
        run: |
          cd backend
          npm test

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm ci

      - name: Run tests (Frontend)
        run: |
          cd frontend
          npm run test:unit

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to production
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          ssh $USER@$HOST << EOF
            cd /home/annael/asili
            git pull origin master
            docker-compose -f docker-compose.prod.yml up -d --build
          EOF
